version: 2
updates:
  # python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
    labels:
      - "Skip Changelog"
      - "dependencies"
  - package-ecosystem: "pip"
    target-branch: "1.0.latest"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
    labels:
      - "Skip Changelog"
      - "dependencies"
  - package-ecosystem: "pip"
    target-branch: "1.1.latest"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
    labels:
      - "Skip Changelog"
      - "dependencies"
  - package-ecosystem: "pip"
    target-branch: "1.2.latest"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
    labels:
      - "Skip Changelog"
      - "dependencies"
  - package-ecosystem: "pip"
    target-branch: "1.3.latest"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
    labels:
      - "Skip Changelog"
      - "dependencies"
